name: spotify_conversations
description: Comment on your Spotify collaborative playlist songs.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^3.10.2
  http: ^0.13.4
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  provider: ^6.0.1
  google_fonts: ^2.1.0
  lottie: ^1.2.1
  firebase_auth: ^3.3.9 
  shared_preferences: ^2.0.13
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  url_launcher: ^6.0.20
  spotify_sdk: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Proxima Nova Rg
      fonts:
        - asset: fonts/proxima_nova.otf
  